<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Copy' => 'Copy',
  'Define Period' => '',
  'Link items to expense positions' => '',
  'Add new record' => 'Add new record',
  'Back' => 'Back',
  'Cancel' => 'Cancel',
  'Create' => 'Create',
  'Data' => 'Data',
  'Delete' => 'Delete',
  'Do you want to delete this item?' => 'Do you want to delete this item?',
  'Fields with <span class="required">*</span> are required.' => 'Fields with <span class="required">*</span> are required.',
  'Invalid request. Please do not repeat this request again.' => 'Invalid request.',
  'Manage' => 'List',
  'Save' => 'Save',
  'The requested page does not exist.' => 'The requested page does not exist.',
  'View' => 'View',
);
